### ISSUE TITLE
Plugin 'com.headwire.aem.tooling.intellij' failed to initialize 

### ISSUE THREAD

**Issue by AxelHo** [headwirecom/aem-ide-tooling-4-intellij#22] opened 2016-11-09 09:31 UTC
Hi,
try to install the plugin in Intellij 2016.1.3 failed 

Plugin 'com.headwire.aem.tooling.intellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: com.headwire.aem.tooling.intellij.console.ConsoleLog PluginClassLoader[com.headwire.aem.tooling.intellij, 0.7.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:412)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:458)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:450)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:61)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by AxelHo** [comment] 2016-11-09 10:48
updated to 
IntelliJ IDEA 2016.1.4
Build #IU-145.2070, built on August 2, 2016
JRE: 1.8.0_92-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

same problem

**Comment by schaefa** [comment] 2016-11-09 16:47
Hi

Lately there are some issues popping up with the plugin that are hard to track down. I checked the 0.7.1 zip file and the class is there in the right location but it could be that the static initializer fail causing this issues. Can you do me a favor and do the following to narrow it down:

1) In IntelliJ go to Help -> Show Log in Explorer (or something alike: https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)
2) Remove our plugin from IntelliJ
2) Shut down IntelliJ
3) Copy away the idea.log file or delete it
4) Start IntelliJ
5) Install the plugin
6) Restart IntelliJ
7) Attach the log file here

I am sorry for the drag but I am working on a Mac and I do not have that issue.

Thanks - Andy Schaefer

**Comment by gittergoing** [comment] 2016-11-11 16:29
I am having the same issue and I am on a Mac. Attached is the log per your request.

Thanks - Shaun English
[idea.log.txt](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/586236/idea.log.txt)

**Comment by schaefa** [comment] 2016-11-16 17:34
@gittergoing I tried the Plugin in Mac OS X 10.12 and the latest IntelliJ CE and it works fine for me.

I will do some more testing and if nothing comes up I will create a version without the Console Log for you to test.

Could you open the Plugin ZIP file and make sure the class is there (just to be on the save side).

**Comment by schaefa** [comment] 2016-11-17 02:04
I still cannot reproduce the issue but it might be a race condition. I did add some NPE guards and avoided class member initialization to see if an exception might cause the issue. I also guarded some of the classes that uses the Console Log from NPEs.

I will soon issue an beta release of 0.7.2. Please give it a try and let me know if that works for you. The plugin might be working but you might have no log statements in the AEM Log. It would be appreciated if you could post an updated idea.log if you see any error statements from the Plugin.

**Comment by schaefa** [comment] 2016-11-17 16:51
Here is the 0.7.2-beta version of the Plugin. It contains guards and adjustments to the ConsoleLog but because I cannot reproduce it this is a shot into the dark. Let me know if that fixes your issues:

https://db.tt/CaZfB5mj

**Comment by schaefa** [comment] 2016-11-22 15:07
I was finally able to reproduce the issue where the automatic start of a Run / Debug Connection is ending up in a deadlock. For now I disabled that feature to make the plugin usable again until we have a fix for it. Please download 0.7.2-beta2 from here: https://db.tt/Q7a1KSlE

**Comment by schaefa** [comment] 2017-03-15 18:11
The plugin release 1.0 has some changes to the way it imports libraries.

As I did not hear anything since November last year I close this. Re-open it if you encounter this issues with release 1.0.

**Closed by schaefa** 2017-03-15 18:11 UTC

**Comment by sameergauba** [comment] 2017-09-06 18:20
Cannot find 1.0 release anywhere and facing this problem.
