### ISSUE TITLE
Maven projects are not shown in Build configuration

### ISSUE THREAD

**Issue by SBPrakash** [headwirecom/aem-ide-tooling-4-intellij#57] opened 2018-03-28 01:06 UTC
I am using latest version of plugin  1.0.3.2  with Intellij 2018.1 I am not seeing the maven projects  in the build configuration to add it the server.. Screenshot here. 
![image](https://user-images.githubusercontent.com/9323430/38002876-76aa98e0-3280-11e8-95f3-cc17b6df480d.png)

**Comment by schaefa** [comment] 2018-03-28 21:44
Please make sure that you have connected the project to a server as the module list is only built during that process.

I might disable the icon while there is no module list but currently I am pretty busy with work.

**Comment by SBPrakash** [comment] 2018-03-28 21:47
In IntelliJ 2017.3 when I start the server projects will get added automatically as defined in pom.xml but in 2018 version of IntelliJ that’s not happening. Also not able to add manually.

**Comment by schaefa** [comment] 2018-03-29 01:35
When I tried to test it today I ran into some issues with threads / deadlocks with the latest IntelliJ CE version. Not sure what is going on. I will try to debug it this week and see if I can find a solution for it.

This is not the first time IntelliJ changes stuff with their threads causing problems like this.

Thanks for you patience as I try to sort this out.

- Andy Schaefer

**Comment by SBPrakash** [comment] 2018-04-08 10:02
Hi Andy,
Sorry to disturb you.. Did you get any chance to look into the issue

**Comment by schaefa** [comment] 2018-04-18 22:09
Hi Prakash

Sorry for the late reply but I was pretty busy with helping a major release of my client.

I looked into it and once more the threading in IntelliJ and/or Java has changed. I fixed it locally but this might not work for you guys. Please let me know if it fixes your issue and if you encounter other issues:

[Releases: ](https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases)

Thanks - Andy Schaefer

**Comment by schaefa** [comment] 2018-04-18 22:37
Can you do the following for me to narrow the issue down:

1. Use IntelliJ to let you know where the Log file is (Help -> Show Log in ...)
2. Stop IntelliJ
3. Move away or delete the idea.log file
4. Start IntelliJ
5. Start the Server Connection
6. Open the Build Dialog
7. Shutdown IntelliJ
8. Attach the log file to this thread

I am not sure what is going wrong but I am assuming that when the Build Dialog is empty then it has issues with creating the Module structure. Keep in mind that the Modules are only listed when the a connection is started.

**Comment by SBPrakash** [comment] 2018-04-19 00:06
Attached the log after as per steps. 
[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1926123/idea.log)

**Comment by schaefa** [comment] 2018-04-19 20:18
Hi Prakash

Your log did not show anything about the AEM Tooling Plugin. I see some errors from other plugins but that should be fine.

I will go ahead and add some logging statements to the way the plugin sets up the Module structure. Unfortunately I cannot increase the log level for our plugin. The only way for me what to go to the IntelliJ installation folder and look for log.xml. There is changed the default log level from INFO to DEBUG:

<priority value="DEBUG"/>

If you could do that change and send me the new log file would help to understand what is going on.

**Comment by SBPrakash** [comment] 2018-04-21 10:05
HI Andy,,

I couldn't find the log.xml in Mac, but I got thread dumps in the logs folder. Attached here. This may help you.
[threadDump-20180421-194854.txt](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1934375/threadDump-20180421-194854.txt)

**Comment by schaefa** [comment] 2018-04-21 19:10
You can find the log.xml on a Mac here:

1. Go to Applications and locate IntelliJ
2. Right click on it and select 'Show Package Content'
3. Go there to 'contents/bin'

There is the log.xml file.

BTW the thread dump did not indicate any issues and I don't think your problem is a threading deadlock issue.

**Comment by SBPrakash** [comment] 2018-04-21 22:27
HI ,

I have changed the log level to DEBUG in log.xml and attached the logs after the steps mentioned the previous comments.



[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1935043/idea.log)


[idea1.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1935044/idea1.log)
[idea2.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1935045/idea2.log)

**Comment by schaefa** [comment] 2018-04-26 01:52
You should see at least this log statement: 'Info message for SSE'. If you see this one: 'Debug message for SSE' then Debug logging is still set up.

Keep in mind that the class names are shortened and so you might not see the log statements. I am looking for logging statements for these classes:

* ServerConnectionManager
* ServerConfigurationManager

Digging deeper I found an issue with updating the Tree Buildup. Please use the attached plugin, make sure logging is set to Debug and try again, thanks.

[AEM IDE Tooling 4 IntelliJ.beta1-2.zip](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1949399/AEM.IDE.Tooling.4.IntelliJ.beta1-2.zip)

**Comment by SBPrakash** [comment] 2018-04-26 02:25
[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1949471/idea.log)
[idea1.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1949472/idea1.log)
[idea2.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1949473/idea2.log)
[Uploading idea3.log…]()


I have attached the logs with the debug enabled mate..

**Comment by schaefa** [comment] 2018-04-26 02:42
Thanks for the quick reply.

What I see in the logs is that there are no Modules reported. I will look into that further and send you a new build with additional logging statements to narrow the problem down.

**Comment by schaefa** [comment] 2018-04-26 04:41
Here's the updated release:

[AEM IDE Tooling 4 IntelliJ.beta1-3.zip](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1949699/AEM.IDE.Tooling.4.IntelliJ.beta1-3.zip)

**Comment by SBPrakash** [comment] 2018-04-26 11:34
This one also it didn't work.. did you see the modules loaded after server has started? I doubt is there something wrong with my Mac

**Comment by schaefa** [comment] 2018-04-26 13:51
The latest version (beta1-3) was not a fix but had additional log statements to investigate why they modules are not loaded. So I need to new log files to get a better understanding what happens on your side as it works for me.

**Comment by SBPrakash** [comment] 2018-04-26 20:42
[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/1952926/idea.log)
Attached the log.. Hope this helps

**Comment by schaefa** [comment] 2018-04-26 21:28
According to your log I see that your are working on ACS Commons, right?

If so can you send me your project so that I can try it out locally.

I see this in the logs:

Get Unified Modules, handled Maven project: ACS AEM Commons Bundle 
Get Unified Modules, Maven project file path: /Workspace/acs-aem-commons/content/acs-aem-commons-content.iml 
Get Unified Modules, Maven project module file: file:///Workspace/acs-aem-commons/content 
Get Unified Modules, handled Maven project: ACS AEM Commons Package 
Get Unified Modules, Maven project file path: /Workspace/acs-aem-commons/content/acs-aem-commons-content.iml 
Get Unified Modules, Maven project module file: file:///Workspace/acs-aem-commons/content 
Get Unified Modules, handled Maven project: ACS AEM Commons Twitter Support Bundle 
Get Unified Modules, Maven project file path: /Workspace/acs-aem-commons/content/acs-aem-commons-content.iml 
Get Unified Modules, Maven project module file: file:///Workspace/acs-aem-commons/content 

This means all your Maven modules are under the same folder (/Workspace/acs-aem-commons/content). This does not seem right.

Cheers - Andy

**Comment by schaefa** [comment] 2018-04-27 00:26
Ok, I checkout ACS Commons and added it to my project. Originally it did not show the modules but complained about the missing filter for content. To fix that I marked content/src/main/content as Resource Root and took that away from content/src/main/content/jcr_root. After restarting IntelliJ the modules would show up just fine and with it the Build Dialog was populated.

If that is not fixing your issue then I need your IntelliJ project (/Workspace/acs-aem-commons).

**Comment by SBPrakash** [comment] 2018-04-30 04:38
It's working now.. but nothing to do with the content or jcr:root folder. i have deleted all the folders related to intellij and freshly installed the project and intellij..

Thanks for your time mate.. Really Appreciated

![image](https://user-images.githubusercontent.com/9323430/39415210-0f93087c-4c84-11e8-98b3-878681dd3e08.png)

**Comment by schaefa** [comment] 2018-05-01 15:18
Cool.

If you want me to have a look into the Mac problem then zip up your project and attach it here so that I can have a look into it.

Thanks - Andy

**Comment by GonzaloCalandria** [comment] 2018-06-25 18:48
I've the same problem, can you help me @schaefa ?

**Comment by schaefa** [comment] 2018-06-25 20:34
@GonzaloCalandria I need your idea.log (for a short file use IntelliJ to find it (Menu -> Help -> Show Log in ...), shutdown IntelliJ, delete the idea.log, start IntelliJ and reproduce the issue).
It would also help if you could provide me with your project or with a sample project that show cases your issue.

**Comment by SBPrakash** [comment] 2018-06-25 20:38
@schaefa for me it was fixed for sometime but later it is broken again. Something is not correct. 

I remember before this issue came when you import thr project in IntelliJ it will automatically recognise the content root and it will show in build config,not nowadays.

**Comment by GonzaloCalandria** [comment] 2018-06-25 20:38
Here's my idea.log but I cannot share the project with you and I don't have another project to send you.. sorry.
[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/2134672/idea.log)

**Comment by schaefa** [comment] 2018-06-25 22:06
@GonzaloCalandria I think I mixed up two issues here. Is your problem related to the Build Configuration (no modules listed) or regarding the Import From issue?

**Comment by GonzaloCalandria** [comment] 2018-06-25 22:10
My problemis about the Build Configuration list being empty

**Comment by schaefa** [comment] 2018-06-25 22:31
AFAIC remember this was an issue related to the content not having the jcr_root folder being marked as source root. Can you check if your content root is marked as resource root (right click on the jcr_root folder -> Mark Directory as -> Bottom should how Unmark as Resource Root, if not then select Resource Root).

If that is not the case then please send me your log file with the logs set to DEBUG.

**Comment by GonzaloCalandria** [comment] 2018-06-27 13:00
@schaefa I did that (Mark the directory as source root) and I'm still seeing the Edit Build Configuration empty. About those logs, how I put those in DEBUG mode?

**Comment by schaefa** [comment] 2018-06-28 14:46
@GonzaloCalandria You need to find the log.xml file (should be located where IntelliJ is installed) and then edit the <root/> section but adjusting the priority line to: <priority value="DEBUG"/>

**Comment by GonzaloCalandria** [comment] 2018-06-28 16:32
Ok @schaefa  I think this is the log in debug mode
[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/2146119/idea.log)

**Comment by schaefa** [comment] 2018-06-28 16:49
Hi @GonzaloCalandria thanks for the log file. Unfortunately this log file has no entries from our plugin so it does not help. Can you do the following:
- Shutdown IntelliJ
- Go to the log files folder and delete, move or rename the existing ones
- Change the log.xml file with this to make sure the name of the logging class is fully qualified:
  <appender name="FILE" class="org.apache.log4j.RollingFileAppender">
    <param name="MaxFileSize" value="1Mb"/>
    <param name="MaxBackupIndex" value="12"/>
    <param name="File" value="$LOG_DIR$/idea.log"/>
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="%d [%7r] %6p - %c - %m \n"/>
    </layout>
  </appender>
- Start IntelliJ
- Open your project (it not already done)
- Open the AEM plugin
- Start the connection
- Click on the Build Configuration
- Copy away the log files (all of them if there are more than one) and post them here

Thanks - Andy Schaefer

**Comment by schaefa** [comment] 2018-06-28 16:56
@GonzaloCalandria I just tested that myself and it is not working as most of the logging statements in our plugin is on TRACE but setting all of it to trace with created big log files (multiple 10MB files just to start it up).

I will try to find a solution where I can set the trace only to the plugin code and let you know.

**Comment by GonzaloCalandria** [comment] 2018-06-28 17:52
@schaefa ok, thank you for all your help! I'll wait for that.

**Comment by GonzaloCalandria** [comment] 2018-06-28 19:46
@schaefa I just got this exception, I don't know if it has anything to do with my problem but maybe can help:
`Must not run under write action
java.lang.RuntimeException: Must not run under write action
	at com.intellij.openapi.vcs.impl.CodeSmellDetectorImpl.findCodeSmells(CodeSmellDetectorImpl.java:109)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener.executeMakeInUIThread(ContentResourceChangeListener.java:296)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener.access$800(ContentResourceChangeListener.java:72)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener$3.run(ContentResourceChangeListener.java:278)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:656)
	at com.headwire.aem.tooling.intellij.util.ExecutionUtil.invokeAndWait(ExecutionUtil.java:67)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener.executeMake(ContentResourceChangeListener.java:274)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener.access$500(ContentResourceChangeListener.java:72)
	at com.headwire.aem.tooling.intellij.communication.ContentResourceChangeListener$2.contentsChanged(ContentResourceChangeListener.java:163)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy19.contentsChanged(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy17.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:890)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:198)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:90)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:185)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by schaefa** [comment] 2018-06-28 20:32
@GonzaloCalandria Thanks, that is a good hint. I ran into the same thing with the Import From action and I know how to fix it. Probably by tomorrow I have a fix.

**Comment by GonzaloCalandria** [comment] 2018-06-28 20:44
@schaefa cool! but that's something to do with the Edit Build Configuration issue?

**Comment by schaefa** [comment] 2018-06-28 20:47
This is part of the verify process when you connect to a remote AEM instance. When that fails then the Module Map is not built and hence the Build Configuration is empty. The Module Map is virtual because it can be based on a remote AEM instance, a local Maven module or both. So each time you connect that Map is rebuilt even though the plugin store the last good version initially.
Anyhow with that exception you cannot deploy whatsoever.

**Comment by schaefa** [comment] 2018-06-29 16:37
@GastonGonzalez I am sorry but this takes a little bit longer. For now I am waiting for some support from JetBrains as I do not understand how to fix this (they require a Read Only thread but I cannot find a way to set this up).

**Comment by GonzaloCalandria** [comment] 2018-07-02 16:45
@schaefa do we have any update about the Edit Build Configuration issue?

**Comment by schaefa** [comment] 2018-07-02 17:36
@GonzaloCalandria No, JetBrains did not provide any solution or suggestion on how to fix that.

**Comment by GonzaloCalandria** [comment] 2018-07-02 18:12
@schaefa this only affect the latest version of IntelliJ (my version is the latest)?

**Comment by schaefa** [comment] 2018-07-02 18:13
@GastonGonzalez I think all versions before 2018.1 should be fine, I think.

**Comment by GonzaloCalandria** [comment] 2018-07-23 14:43
Hey @schaefa did you find a solution for the problem with empty projects in the build configuration?

**Comment by schaefa** [comment] 2018-07-23 18:30
@GonzaloCalandria Sorry, I had no time to look into this. I am just wondering if the Build Configuration is empty isn't then also the list of module in the Server Configuration Details empty?

For right now JetBrains did not respond to my forum question and I did not have time to look into the issue with the failing Code Smell Check.

I am wondering if for now I should make the Code Smell Check optional (flag in the configuration) to get past that.

**Comment by SBPrakash** [comment] 2018-07-23 18:47
Hi @schaefa,

For me as well it’s not working again. I have tried manually adding the modules to serverconfiguration.xml under .idea folder and restart the IntelliJ to take effect. But when I try to start the server while the modules are listed already I got the error as modules are not bound to maven project.

**Comment by schaefa** [comment] 2018-07-23 19:53
@GonzaloCalandria Just released https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases/tag/1.0.3.4-beta2 Beta 2 which should fix the issue with the Code Smell Detector.

For the Empty Build Dialog does anyone see an exception.

@SBPrakash I cannot find that message in my project. Do you see this in the idea.log or in the UI. If you see a stack trace or any further info please post it here - thanks.

**Comment by GonzaloCalandria** [comment] 2018-07-23 21:04
@schaefa that version didn't worked... Build Configarion still empty :(

**Comment by schaefa** [comment] 2018-07-24 00:35
@GonzaloCalandria I did not expect that this would fix the empty build configuration.

Without having a project where I can reproduce I need some better logging statements. I updated the beta2 release with additional logging statements but the log level needs to be setup for DEBUG. Here is the initial setup:

### Logging

In order to set the correct logging settings the user needs to do the following:

1. Go to the IntelliJ IDEA program root
2. Find the log.xml file (Mac: /bin/contents)
3. Edit that file by adjusting the following:
	1. Set the Category Pattern right (we need the FQN of the classes) by removing the 30.30 from '%30.30c'
```
  <appender name="FILE" class="org.apache.log4j.RollingFileAppender">
    <param name="MaxFileSize" value="1Mb"/>
    <param name="MaxBackupIndex" value="12"/>
    <param name="File" value="$LOG_DIR$/idea.log"/>
    <layout class="org.apache.log4j.PatternLayout">
      <param name="ConversionPattern" value="%d [%7r] %6p - %c - %m \n"/>
    </layout>
  </appender>
```
	2. Set the log level to DEBUG
```
  <root>
    <priority value="DEBUG"/>
    <appender-ref ref="DIALOG"/>
    <appender-ref ref="FILE"/>
  </root>
```
4. Restart IntelliJ IDEA
5. Go to the IntelliJ Log files and look for this line: '- Debug message for SSE'. If found
debug settings are up and running

### Update the Plugin

Please update the plugin to the latest release including a beta from the GitHub
release page: https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases

### Remove the Existing Log Files

This needs to be done every time before creating a log file that is posted here otherwise it is hard to
know what is causing the issue.

1. Use IntelliJ to let you know where the Log file is (Help -> Show Log in ...)
2. Stop IntelliJ
3. Move away or delete all the idea.log file (including the older copies)
4. Start IntelliJ

**Comment by GonzaloCalandria** [comment] 2018-08-02 19:49
@schaefa sorry for my delay in my response.
Here's my log file
[idea.log](https://github.com/headwirecom/aem-ide-tooling-4-intellij/files/2254958/idea.log)

**Comment by schaefa** [comment] 2018-08-02 21:26
@GonzaloCalandria Did you try to connect to the AEM / Sling instance by run or debug the connection ?
Does the Connection Panel show the list of modules?

**Comment by GonzaloCalandria** [comment] 2018-08-03 12:49
@schaefa yes, I can connect to an instance but I think I can't see the list of modules... but could you please tell me which one is the Connection Panel to be sure?

**Comment by schaefa** [comment] 2018-08-06 21:35
<img width="423" alt="screenshot 2018-08-06 14 06 58" src="https://user-images.githubusercontent.com/209539/43741076-0647f4f8-9982-11e8-8758-982b5e515880.png">

Can you do the following:
- Stop IntelliJ
- Delete the log file
- Start IntelliJ
- Start your connection in either run or debug mode
- Expand the current connection configuration (probably already done)
- Take a picture and add it here
- Open the Manage Build Configuration
- Post your log file

Just to elaborate here. The list of modules is created when the connection is started (actually this is done during the verification). That said if you see the list of modules but no modules in the Build Dialog then something else is wrong there but I do not see anything in the logs so I assume there is an issue with the module list creation.
If I find time I will move the creation of the module list to when the project is loaded but I am not sure if that is possible due to timing issues.

**Comment by schaefa** [comment] 2021-01-25 16:25
Due to high maintenance we decided to End the Development of this plugin.

**Closed by schaefa** 2021-01-25 16:25 UTC
